export const YearlyTimeTable = [
  {
    month: "January",
    times: [
      {
        dateRange: "1-10",
        fajr: "6:45 AM",
        zuhr: "1:00 PM",
        asr: "3:45 PM",
        maghrib: "Sunset",
        isha: "8:00 PM",
      },
      {
        dateRange: "11-20",
        fajr: "6:45 AM",
        zuhr: "1:00 PM",
        asr: "4:00 PM",
        maghrib: "Sunset",
        isha: "8:00 PM",
      },
      {
        dateRange: "21-31",
        fajr: "6:30 AM",
        zuhr: "1:00 PM",
        asr: "4:00 PM",
        maghrib: "Sunset",
        isha: "8:00 PM",
      },
    ],
  },
  {
    month: "February",
    times: [
      {
        dateRange: "1-10",
        fajr: "6:15 AM",
        zuhr: "1:00 PM",
        asr: "4:30 PM",
        maghrib: "Sunset",
        isha: "8:00 PM",
      },
      {
        dateRange: "11-20",
        fajr: "6:00 AM",
        zuhr: "1:00 PM",
        asr: "4:45 PM",
        maghrib: "Sunset",
        isha: "8:00 PM",
      },
      {
        dateRange: "21-29",
        fajr: "6:15 AM",
        zuhr: "1:00 PM",
        asr: "4:45 PM",
        maghrib: "Sunset",
        isha: "8:00 PM",
      },
    ],
  },
  {
    month: "March",
    times: [
      {
        dateRange: "D/L-20",
        fajr: "6:45 AM",
        zuhr: "2:00 PM",
        asr: "6:00 PM",
        maghrib: "Sunset",
        isha: "9:15 PM",
      },
      {
        dateRange: "21-31",
        fajr: "6:30 AM",
        zuhr: "2:00 PM",
        asr: "6:00 PM",
        maghrib: "Sunset",
        isha: "9:30 PM",
      },
    ],
  },
  {
    month: "April",
    times: [
      {
        dateRange: "1-10",
        fajr: "6:15 AM",
        zuhr: "2:00 PM",
        asr: "6:30 PM",
        maghrib: "Sunset",
        isha: "9:30 PM",
      },
      {
        dateRange: "11-20",
        fajr: "6:00 AM",
        zuhr: "2:00 PM",
        asr: "6:30 PM",
        maghrib: "Sunset",
        isha: "9:45 PM",
      },
      {
        dateRange: "21-30",
        fajr: "5:45 AM",
        zuhr: "2:00 PM",
        asr: "6:30 PM",
        maghrib: "Sunset",
        isha: "10:00 PM",
      },
    ],
  },
  {
    month: "May",
    times: [
      {
        dateRange: "1-10",
        fajr: "5:30 AM",
        zuhr: "2:00 PM",
        asr: "7:00 PM",
        maghrib: "Sunset",
        isha: "10:15 PM",
      },
      {
        dateRange: "11-20",
        fajr: "5:15 AM",
        zuhr: "2:00 PM",
        asr: "7:00 PM",
        maghrib: "Sunset",
        isha: "10:30 PM",
      },
      {
        dateRange: "21-31",
        fajr: "5:00 AM",
        zuhr: "2:00 PM",
        asr: "7:00 PM",
        maghrib: "Sunset",
        isha: "10:45 PM",
      },
    ],
  },
  {
    month: "June",
    times: [
      {
        dateRange: "1-10",
        fajr: "5:00 AM",
        zuhr: "2:00 PM",
        asr: "7:30 PM",
        maghrib: "Sunset",
        isha: "10:55 PM",
      },
      {
        dateRange: "11-20",
        fajr: "5:00 AM",
        zuhr: "2:00 PM",
        asr: "7:30 PM",
        maghrib: "Sunset",
        isha: "10:55 PM",
      },
      {
        dateRange: "21-30",
        fajr: "5:00 AM",
        zuhr: "2:00 PM",
        asr: "7:30 PM",
        maghrib: "Sunset",
        isha: "10:55 PM",
      },
    ],
  },
  {
    month: "July",
    times: [
      {
        dateRange: "1-10",
        fajr: "5:00 AM",
        zuhr: "2:00 PM",
        asr: "7:30 PM",
        maghrib: "Sunset",
        isha: "10:50 PM",
      },
      {
        dateRange: "11-20",
        fajr: "5:15 AM",
        zuhr: "2:00 PM",
        asr: "7:30 PM",
        maghrib: "Sunset",
        isha: "10:50 PM",
      },
      {
        dateRange: "21-31",
        fajr: "5:30 AM",
        zuhr: "2:00 PM",
        asr: "7:00 PM",
        maghrib: "Sunset",
        isha: "10:40 PM",
      },
    ],
  },
  {
    month: "August",
    times: [
      {
        dateRange: "1-10",
        fajr: "5:15 AM",
        zuhr: "2:00 PM",
        asr: "7:00 PM",
        maghrib: "Sunset",
        isha: "10:30 PM",
      },
      {
        dateRange: "11-20",
        fajr: "5:30 AM",
        zuhr: "2:00 PM",
        asr: "6:45 PM",
        maghrib: "Sunset",
        isha: "10:15 PM",
      },
      {
        dateRange: "21-31",
        fajr: "5:45 AM",
        zuhr: "2:00 PM",
        asr: "6:30 PM",
        maghrib: "Sunset",
        isha: "9:45 PM",
      },
    ],
  },
  {
    month: "September",
    times: [
      {
        dateRange: "1-10",
        fajr: "6:00 AM",
        zuhr: "2:00 PM",
        asr: "6:00 PM",
        maghrib: "Sunset",
        isha: "9:30 PM",
      },
      {
        dateRange: "11-20",
        fajr: "6:15 AM",
        zuhr: "2:00 PM",
        asr: "5:30 PM",
        maghrib: "Sunset",
        isha: "9:15 PM",
      },
      {
        dateRange: "21-30",
        fajr: "6:15 AM",
        zuhr: "2:00 PM",
        asr: "5:00 PM",
        maghrib: "Sunset",
        isha: "9:00 PM",
      },
    ],
  },
  {
    month: "October",
    times: [
      {
        dateRange: "1-10",
        fajr: "6:30 AM",
        zuhr: "2:00 PM",
        asr: "5:00 PM",
        maghrib: "Sunset",
        isha: "8:30 PM",
      },
      {
        dateRange: "11-20",
        fajr: "6:30 AM",
        zuhr: "2:00 PM",
        asr: "4:45 PM",
        maghrib: "Sunset",
        isha: "8:30 PM",
      },
      {
        dateRange: "21-31",
        fajr: "6:45 AM",
        zuhr: "2:00 PM",
        asr: "4:30 PM",
        maghrib: "Sunset",
        isha: "8:00 PM",
      },
    ],
  },
  {
    month: "November",
    times: [
      {
        dateRange: "Before D/L",
        fajr: "6:45 AM",
        zuhr: "2:00 PM",
        asr: "5:00 PM",
        maghrib: "Sunset",
        isha: "8:00 PM",
      },
      {
        dateRange: "After D/L",
        fajr: "6:15 AM",
        zuhr: "1:00 PM",
        asr: "3:45 PM",
        maghrib: "Sunset",
        isha: "8:00 PM",
      },
      {
        dateRange: "11-20",
        fajr: "6:30 AM",
        zuhr: "1:00 PM",
        asr: "3:30 PM",
        maghrib: "Sunset",
        isha: "8:00 PM",
      },
      {
        dateRange: "21-30",
        fajr: "6:45 AM",
        zuhr: "1:00 PM",
        asr: "3:30 PM",
        maghrib: "Sunset",
        isha: "8:00 PM",
      },
    ],
  },
  {
    month: "December",
    times: [
      {
        dateRange: "1-10",
        fajr: "6:45 AM",
        zuhr: "1:00 PM",
        asr: "3:30 PM",
        maghrib: "Sunset",
        isha: "8:00 PM",
      },
      {
        dateRange: "11-20",
        fajr: "6:45 AM",
        zuhr: "1:00 PM",
        asr: "3:30 PM",
        maghrib: "Sunset",
        isha: "8:00 PM",
      },
      {
        dateRange: "21-31",
        fajr: "6:45 AM",
        zuhr: "1:00 PM",
        asr: "3:30 PM",
        maghrib: "Sunset",
        isha: "8:00 PM",
      },
    ],
  },
];
